=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenAIClient::AssistantApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AssistantApi' do
  before do
    # run before each test
    @instance = OpenAIClient::AssistantApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssistantApi' do
    it 'should create an instance of AssistantApi' do
      expect(@instance).to be_instance_of(OpenAIClient::AssistantApi)
    end
  end

  # unit tests for modify_assistant
  # Modifies an assistant.
  # @param body 
  # @param assistant_id The ID of the assistant to modify.
  # @param [Hash] opts the optional parameters
  # @return [AssistantObject]
  describe 'modify_assistant test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
