=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenAIClient::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = OpenAIClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(OpenAIClient::DefaultApi)
    end
  end

  # unit tests for admin_api_keys_create
  # Create an organization admin API key
  # Create a new admin-level API key for the organization.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [AdminApiKey]
  describe 'admin_api_keys_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_api_keys_delete
  # Delete an organization admin API key
  # Delete the specified admin API key.
  # @param key_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2002]
  describe 'admin_api_keys_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_api_keys_get
  # Retrieve a single organization API key
  # Get details for a specific organization API key by its ID.
  # @param key_id 
  # @param [Hash] opts the optional parameters
  # @return [AdminApiKey]
  describe 'admin_api_keys_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_api_keys_list
  # List organization API keys
  # Retrieve a paginated list of organization admin API keys.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @option opts [String] :order 
  # @option opts [Integer] :limit 
  # @return [ApiKeyList]
  describe 'admin_api_keys_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
