=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.63
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenAIClient::RealtimeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RealtimeApi' do
  before do
    # run before each test
    @instance = OpenAIClient::RealtimeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RealtimeApi' do
    it 'should create an instance of RealtimeApi' do
      expect(@instance).to be_instance_of(OpenAIClient::RealtimeApi)
    end
  end

  # unit tests for create_realtime_session
  # Create an ephemeral API token for use in client-side applications with the Realtime API. Can be configured with the same session parameters as the &#x60;session.update&#x60; client event.  It responds with a session object, plus a &#x60;client_secret&#x60; key which contains a usable ephemeral API token that can be used to authenticate browser clients for the Realtime API. 
  # @param body Create an ephemeral API key with the given session configuration.
  # @param [Hash] opts the optional parameters
  # @return [RealtimeSessionCreateResponse]
  describe 'create_realtime_session test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
