=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenAIClient::CompleteUploadRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CompleteUploadRequest' do
  before do
    # run before each test
    @instance = OpenAIClient::CompleteUploadRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CompleteUploadRequest' do
    it 'should create an instance of CompleteUploadRequest' do
      expect(@instance).to be_instance_of(OpenAIClient::CompleteUploadRequest)
    end
  end
  describe 'test attribute "part_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "md5"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
