=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenAIClient::CreateUploadRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CreateUploadRequest' do
  before do
    # run before each test
    @instance = OpenAIClient::CreateUploadRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateUploadRequest' do
    it 'should create an instance of CreateUploadRequest' do
      expect(@instance).to be_instance_of(OpenAIClient::CreateUploadRequest)
    end
  end
  describe 'test attribute "filename"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "purpose"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["assistants", "batch", "fine-tune", "vision"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.purpose = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "bytes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "mime_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
