=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.63
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenAIClient::CreateChatCompletionRequestAudio
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CreateChatCompletionRequestAudio' do
  before do
    # run before each test
    @instance = OpenAIClient::CreateChatCompletionRequestAudio.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateChatCompletionRequestAudio' do
    it 'should create an instance of CreateChatCompletionRequestAudio' do
      expect(@instance).to be_instance_of(OpenAIClient::CreateChatCompletionRequestAudio)
    end
  end
  describe 'test attribute "voice"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["alloy", "ash", "ballad", "coral", "echo", "sage", "shimmer", "verse"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.voice = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "format"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["wav", "mp3", "flac", "opus", "pcm16"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.format = value }.not_to raise_error
      # end
    end
  end

end
