=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenAIClient::FileSearchRankingOptions
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FileSearchRankingOptions' do
  before do
    # run before each test
    @instance = OpenAIClient::FileSearchRankingOptions.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FileSearchRankingOptions' do
    it 'should create an instance of FileSearchRankingOptions' do
      expect(@instance).to be_instance_of(OpenAIClient::FileSearchRankingOptions)
    end
  end
  describe 'test attribute "ranker"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["auto", "default_2024_08_21"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.ranker = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "score_threshold"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
