=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.54
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenAIClient::MessageDeltaContentTextObjectText
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MessageDeltaContentTextObjectText' do
  before do
    # run before each test
    @instance = OpenAIClient::MessageDeltaContentTextObjectText.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessageDeltaContentTextObjectText' do
    it 'should create an instance of MessageDeltaContentTextObjectText' do
      expect(@instance).to be_instance_of(OpenAIClient::MessageDeltaContentTextObjectText)
    end
  end
  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "annotations"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
