=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.54
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenAIClient::VectorStoreFileObjectLastError
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VectorStoreFileObjectLastError' do
  before do
    # run before each test
    @instance = OpenAIClient::VectorStoreFileObjectLastError.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VectorStoreFileObjectLastError' do
    it 'should create an instance of VectorStoreFileObjectLastError' do
      expect(@instance).to be_instance_of(OpenAIClient::VectorStoreFileObjectLastError)
    end
  end
  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["internal_error", "file_not_found", "parsing_error", "unhandled_mime_type"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.code = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
