=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.63
=end

require 'date'

module OpenAIClient
  class AuditLogEventType
    API_KEYCREATED = 'api_key.created'.freeze
    API_KEYUPDATED = 'api_key.updated'.freeze
    API_KEYDELETED = 'api_key.deleted'.freeze
    INVITESENT = 'invite.sent'.freeze
    INVITEACCEPTED = 'invite.accepted'.freeze
    INVITEDELETED = 'invite.deleted'.freeze
    LOGINSUCCEEDED = 'login.succeeded'.freeze
    LOGINFAILED = 'login.failed'.freeze
    LOGOUTSUCCEEDED = 'logout.succeeded'.freeze
    LOGOUTFAILED = 'logout.failed'.freeze
    ORGANIZATIONUPDATED = 'organization.updated'.freeze
    PROJECTCREATED = 'project.created'.freeze
    PROJECTUPDATED = 'project.updated'.freeze
    PROJECTARCHIVED = 'project.archived'.freeze
    SERVICE_ACCOUNTCREATED = 'service_account.created'.freeze
    SERVICE_ACCOUNTUPDATED = 'service_account.updated'.freeze
    SERVICE_ACCOUNTDELETED = 'service_account.deleted'.freeze
    RATE_LIMITUPDATED = 'rate_limit.updated'.freeze
    RATE_LIMITDELETED = 'rate_limit.deleted'.freeze
    USERADDED = 'user.added'.freeze
    USERUPDATED = 'user.updated'.freeze
    USERDELETED = 'user.deleted'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = AuditLogEventType.constants.select { |c| AuditLogEventType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #AuditLogEventType" if constantValues.empty?
      value
    end
  end
end
