=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'date'

module OpenAI
  # Represents a step in execution of a run. 
  class RunStepObject
    # The identifier of the run step, which can be referenced in API endpoints.
    attr_accessor :id

    # The object type, which is always `assistant.run.step``.
    attr_accessor :object

    # The Unix timestamp (in seconds) for when the run step was created.
    attr_accessor :created_at

    # The ID of the [assistant](/docs/api-reference/assistants) associated with the run step.
    attr_accessor :assistant_id

    # The ID of the [thread](/docs/api-reference/threads) that was run.
    attr_accessor :thread_id

    # The ID of the [run](/docs/api-reference/runs) that this run step is a part of.
    attr_accessor :run_id

    # The type of run step, which can be either `message_creation` or `tool_calls`.
    attr_accessor :type

    # The status of the run, which can be either `in_progress`, `cancelled`, `failed`, `completed`, or `expired`.
    attr_accessor :status

    # The details of the run step.
    attr_accessor :step_details

    attr_accessor :last_error

    # The Unix timestamp (in seconds) for when the run step expired. A step is considered expired if the parent run is expired.
    attr_accessor :expired_at

    # The Unix timestamp (in seconds) for when the run step was cancelled.
    attr_accessor :cancelled_at

    # The Unix timestamp (in seconds) for when the run step failed.
    attr_accessor :failed_at

    # The Unix timestamp (in seconds) for when the run step completed.
    attr_accessor :completed_at

    # Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long. 
    attr_accessor :metadata

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'object' => :'object',
        :'created_at' => :'created_at',
        :'assistant_id' => :'assistant_id',
        :'thread_id' => :'thread_id',
        :'run_id' => :'run_id',
        :'type' => :'type',
        :'status' => :'status',
        :'step_details' => :'step_details',
        :'last_error' => :'last_error',
        :'expired_at' => :'expired_at',
        :'cancelled_at' => :'cancelled_at',
        :'failed_at' => :'failed_at',
        :'completed_at' => :'completed_at',
        :'metadata' => :'metadata'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Object',
        :'object' => :'Object',
        :'created_at' => :'Object',
        :'assistant_id' => :'Object',
        :'thread_id' => :'Object',
        :'run_id' => :'Object',
        :'type' => :'Object',
        :'status' => :'Object',
        :'step_details' => :'Object',
        :'last_error' => :'Object',
        :'expired_at' => :'Object',
        :'cancelled_at' => :'Object',
        :'failed_at' => :'Object',
        :'completed_at' => :'Object',
        :'metadata' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'expired_at',
        :'cancelled_at',
        :'failed_at',
        :'completed_at',
        :'metadata'
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenAI::RunStepObject` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenAI::RunStepObject`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'object')
        self.object = attributes[:'object']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'assistant_id')
        self.assistant_id = attributes[:'assistant_id']
      end

      if attributes.key?(:'thread_id')
        self.thread_id = attributes[:'thread_id']
      end

      if attributes.key?(:'run_id')
        self.run_id = attributes[:'run_id']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'step_details')
        self.step_details = attributes[:'step_details']
      end

      if attributes.key?(:'last_error')
        self.last_error = attributes[:'last_error']
      end

      if attributes.key?(:'expired_at')
        self.expired_at = attributes[:'expired_at']
      end

      if attributes.key?(:'cancelled_at')
        self.cancelled_at = attributes[:'cancelled_at']
      end

      if attributes.key?(:'failed_at')
        self.failed_at = attributes[:'failed_at']
      end

      if attributes.key?(:'completed_at')
        self.completed_at = attributes[:'completed_at']
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @object.nil?
        invalid_properties.push('invalid value for "object", object cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @assistant_id.nil?
        invalid_properties.push('invalid value for "assistant_id", assistant_id cannot be nil.')
      end

      if @thread_id.nil?
        invalid_properties.push('invalid value for "thread_id", thread_id cannot be nil.')
      end

      if @run_id.nil?
        invalid_properties.push('invalid value for "run_id", run_id cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @step_details.nil?
        invalid_properties.push('invalid value for "step_details", step_details cannot be nil.')
      end

      if @last_error.nil?
        invalid_properties.push('invalid value for "last_error", last_error cannot be nil.')
      end

      if @expired_at.nil?
        invalid_properties.push('invalid value for "expired_at", expired_at cannot be nil.')
      end

      if @cancelled_at.nil?
        invalid_properties.push('invalid value for "cancelled_at", cancelled_at cannot be nil.')
      end

      if @failed_at.nil?
        invalid_properties.push('invalid value for "failed_at", failed_at cannot be nil.')
      end

      if @completed_at.nil?
        invalid_properties.push('invalid value for "completed_at", completed_at cannot be nil.')
      end

      if @metadata.nil?
        invalid_properties.push('invalid value for "metadata", metadata cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @object.nil?
      object_validator = EnumAttributeValidator.new('Object', ['assistant.run.step'])
      return false unless object_validator.valid?(@object)
      return false if @created_at.nil?
      return false if @assistant_id.nil?
      return false if @thread_id.nil?
      return false if @run_id.nil?
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('Object', ['message_creation', 'tool_calls'])
      return false unless type_validator.valid?(@type)
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('Object', ['in_progress', 'cancelled', 'failed', 'completed', 'expired'])
      return false unless status_validator.valid?(@status)
      return false if @step_details.nil?
      return false if @last_error.nil?
      return false if @expired_at.nil?
      return false if @cancelled_at.nil?
      return false if @failed_at.nil?
      return false if @completed_at.nil?
      return false if @metadata.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] object Object to be assigned
    def object=(object)
      validator = EnumAttributeValidator.new('Object', ['assistant.run.step'])
      unless validator.valid?(object)
        fail ArgumentError, "invalid value for \"object\", must be one of #{validator.allowable_values}."
      end
      @object = object
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('Object', ['message_creation', 'tool_calls'])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('Object', ['in_progress', 'cancelled', 'failed', 'completed', 'expired'])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          object == o.object &&
          created_at == o.created_at &&
          assistant_id == o.assistant_id &&
          thread_id == o.thread_id &&
          run_id == o.run_id &&
          type == o.type &&
          status == o.status &&
          step_details == o.step_details &&
          last_error == o.last_error &&
          expired_at == o.expired_at &&
          cancelled_at == o.cancelled_at &&
          failed_at == o.failed_at &&
          completed_at == o.completed_at &&
          metadata == o.metadata
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, object, created_at, assistant_id, thread_id, run_id, type, status, step_details, last_error, expired_at, cancelled_at, failed_at, completed_at, metadata].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        OpenAI.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
